spring.application.name=toyota-hr-portal

# ===============================
# MYSQL CONNECTION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/hr_portal?useSSL=false&serverTimezone=UTC
#3306 portunda çalışan MySQLe bağlanarak hr_portal veritabanını kullanacağız.
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
# Java Entity'lerimi sürekli takip et. Yeni bir Entity eklersem MySQL'de otomatik tablo oluştur.
# Alan eklersem tabloyu güncelle.
spring.jpa.show-sql=true
# Hibernate'in çalıştırdığı SQL sorgularını IntelliJ'nin konsolunda göreceğiz.
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
